name: entity_state
description: Helper construct basic redux state in Flutter project.
version: 1.0.0
author: Kushagra Saxena
homepage: https://devslane.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: any

dev_dependencies:
